### ISSUE TITLE
error in train.py

### ISSUE THREAD

**Issue by qizhao1** [Kyubyong/deepvoice3#11]
Hi, kyubyong, thank for your great work, here i met one error, stated below:

/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "train.py", line 103, in <module>
    g = Graph(); print("Training Graph loaded")
  File "train.py", line 46, in __init__
    self.keys, self.vals = encoder(self.x, training=training) # (N, Tx, e)
  File "/home/zqi/zq/TTS/deepvoice3/networks.py", line 39, in encoder
    scope="encoder_conv_{}".format(i)) # (N, Tx, c)
  File "/home/zqi/zq/TTS/deepvoice3/modules.py", line 110, in conv_block
    outputs = glu(outputs)
  File "/home/zqi/zq/TTS/deepvoice3/modules.py", line 54, in glu
    a, b = tf.split(inputs, 2, -1)  # (N, Tx, c) * 2
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 1214, in split
    split_dim=axis, num_split=num_or_size_splits, value=value, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 3261, in _split
    num_split=num_split, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2508, in create_op
    set_shapes_for_outputs(ret)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1873, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1823, in call_with_requiring
    eturn call_cpp_shape_fn(op, require_shape_fn=True)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/common_shapes.py", line 610, in call_cpp_shape_fn
    debug_python_shape_fn, require_shape_fn)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/common_shapes.py", line 676, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)

ValueError: **Dimension size, given by scalar input 0, must be non-negative but is -1 for 'encoder/encoder/encoder_conv/encoder_conv_0/split' (op: 'Split') with input shapes: [], [16,180,128] and with computed input tensors: input[0] = <-1>.**

**Comment by qizhao1** [comment]
I have got the answer, to update the tensorflow and use the GPU to lift speed.
